### ISSUE TITLE
fresh air system

### ISSUE THREAD

**Issue by Matincz** [dext0r/airmx#3]
Can you connect to the fresh air system? Thank you very much.

**Comment by ThomasKwok0605** [comment]
Yes, really need it,  the fresh air  ventilator is also using the same way to remote control,  it would be of great help if they can be supported.

**Comment by xuzhe1224** [comment]
need it!

**Comment by xuzhe1224** [comment]
Is there any progress?

**Comment by dext0r** [comment]
I don't have fresh air system so it'll be hard to add support for it.
