### ISSUE TITLE
ESP8266 notwork

### ISSUE THREAD

**Issue by lichao-zh** [dext0r/airmx#5]
Hello, I tried using ESP8266 and successfully created and connected to WiFi, but I cannot open the i.airmx.cn page and it will not display "Airmx addon" Is there a possible reason?

![wifi page](https://github.com/user-attachments/assets/d0c3076e-c70f-4592-a206-7d8b04e82851)

**Comment by lichao-zh** [comment]
Find the problem. The add-on is not installed correctly, and the hostname of config_flow.py needs to be consistent with the add-on

**Comment by mintmilk** [comment]
same problem，How to solve ? Please~
